### ISSUE TITLE
package does not work with npm 7

### ISSUE THREAD

**Issue by hawser86** [mkls/npm-audit-haphap#2]
Hi,

After updating npm from 6.14.6 to 7.5.4 I received the following error

```
> npm-audit-haphap --validate-with-filter

[PROJECT_DIR]/node_modules/npm-audit-haphap/index.js:28
  const filteredAdvisories = Object.values(auditReport.advisories).filter(
                                    ^

TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at handleValidation ([PROJECT_DIR]/node_modules/npm-audit-haphap/index.js:28:37)
    at [PROJECT_DIR]/node_modules/npm-audit-haphap/index.js:20:21
    at ChildProcess.exithandler (child_process.js:294:7)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12)
npm ERR! code 1
npm ERR! path [PROJECT_DIR]
npm ERR! command failed
npm ERR! command sh -c npm-audit-haphap --validate-with-filter

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/[USER_NAME]/.npm/_logs/2021-02-15T12_14_43_751Z-debug.log
npm ERR! code 1
npm ERR! path [PROJECT_DIR]
npm ERR! command failed
npm ERR! command sh -c npm run audit && npm run lint && npm run test:once

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/[USER_NAME]/.npm/_logs/2021-02-15T12_14_43_792Z-debug.log
```

Can you look into it?

**Comment by hawser86** [comment]
Hi,

It looks like the issue has been resolved in v1.2.1.

Thanks
